### ISSUE TITLE
Modify selection for wrapped struct

### ISSUE THREAD

**Issue by johannes-riecken** [perlancar/perl-Data-CSel#2]
I'm having fun using CSel now. Looking through the examples and documentation I couldn't find a way to modify the selection values, which would make the library a lot more useful. Do you have an idea how I could do that?

Here's what I tried:
```
#!/usr/bin/perl -w
use v5.28;
use Data::CSel qw(csel);
use Data::CSel::WrapStruct qw(wrap_struct);
use Data::Dumper;

my $data = [0, 1, 0, 1];
my $tree = wrap_struct($data);
my $opts = { class_prefixes => ["Data::CSel::WrapStruct"] };
my @res = csel $opts, 'Scalar[value == 1]', $tree;
for (@res) {
    $_->[0]->$* = 'XXX';
}
say Dumper $tree->[0];
```

This prints the original list, but I would like to get `[0, 'XXX', 0, 'XXX']`.

**Comment by perlancar** [comment]
Hi,

I've managed to hack on Data::CSel::WrapStruct today and released
Data-CSel-WrapStruct 0.005. What you want is now possible using the value()
method instead of accessing the object storage directly. From the example:

    use Data::CSel qw(csel);
    use Data::CSel::WrapStruct qw(wrap_struct unwrap_tree);
    use Data::Dump qw(dd);

    my $data = [
        0,
        1,
        [2, ["two","dua"], {url=>"http://example.com/two.jpg"},
["even","prime"]],
        3,
        [4, ["four","empat"], {}, ["even"]],
    ];

    my $tree = wrap_struct($data);
    my @posint_scalar_nodes =
csel({class_prefixes=>["Data::CSel::WrapStruct"]}, "Scalar[value > 0]",
$tree);
    for (@posint_scalar_nodes) { $_->value( $_->value * 10 ) }

    dd unwrap_tree($data);

will print:

    [
        0,
        10,
        [20, ["two","dua"], {url=>"http://example.com/two.jpg"},
["even","prime"]],
        30,
        [40, ["four","empat"], {}, ["even"]],
    ];

Regards,
perlancar
